---

- name: My 1st Play
  # hosts: javadev
  hosts: localhost
  remote_user: eoliosi

  tasks:
  # - name: List file
  #   register: lfile
  #   shell:
  #     cmd: ls -hla
  # - debug: var=lfile.stdout_lines

  - name: Pwd
    become_user: root
    register: pwd
    shell:
      cmd: pwd
  - debug: var=pwd.stdout_lines

  - name: Touch the same file
    file:
      path: /home/eoliosi/prova.txt
      state: touch
      mode: u+rw,g-wx,o-rwx
