version: "3.9"
services:
  ansible:
    build: 
      context: .
      #dockerfile: Dockerfile
    #image: c8-systemd:latest
    ports:
      #IPADDR:HOSTPORT:CONTAINERPORT
      - "22:22"
      - "9000:80"
    privileged: true
    tty: true
    #container_name: c8-systemd-ansible
    
